### PR TITLE
[msvc] Build skia using CMake for msvc compat

### PR DESCRIPTION
**Pull request by vvuk**
This switches the build to cmake on all platforms.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/skia/97)

### CODE REVIEW

**Comment by metajack** [comment]
Just questions about the pkg-config/cmake block. r=me with updates to those.
 
@bors-servo delegate+

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 59 \[r2\]](https://reviewable.io:443/reviews/servo/skia/97#-KMfCC3ieNTYMoplQcXa:-KMfCC3ieNTYMoplQcXb:-645041576) ([raw file](https://github.com/servo/skia/blob/357fdd9fb695a0ebf53c2a7ecf7cf6e45adf0867/CMakeLists.txt#L59)):*
> ```CMake
>   include_directories($ENV{DEP_FREETYPE_OUTDIR}/include)
> else()
>   # We need to work with older pkg-config
> ```

You said this actually is about cmake.

Do we need to support older cmake? Is that deployed somewhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/skia/97#-:-KMfCZ_7f72uPyjf7eGF:-766351977)*

**Comment by vvuk** [comment]
> Do we need to support older cmake? Is that deployed somewhere?

Ubuntu 14.04 LTS has a too-old cmake, which is what my Linux build was.  The just-released (end of April) 16.04 LTS release has a new enough cmake.  I think the CI builders also had a too-old cmake.  So, up to you if you want to support the older one or not :)

**Comment by metajack** [comment]
@vvuk Yeah, we want to support 14.04 I think. At least a little while longer.

**Pull request merged**
