### PR TITLE
Convert SkNativeSharedGLContext to a rust struct

### PR DESCRIPTION
**Pull request by mrobinson**
This has several benefits. The first is that we can rework things so
that native surface details are passed to the struct instead of stolen
from it. This allows us to reuse native surfaces instead of having them
created each time we need a new GPU rasterization context. Because of
this the commit renames SkNativeSharedGLContext to
GPURasterizationContext.

The second benefit is that we now depend less on the internal workings of
Skia, which should make upgrading Skia much, much easier.

### CODE REVIEW

**Comment by mrobinson** [comment]
@pcwalton @jdm @glennw This PR should make upgrading Skia easier and also eventually allow us to avoid having to recreate framebuffers every time we do GPU rasterization.

**Comment by pcwalton** [comment]
The overall approach looks fine to me, but I was wondering if we could reduce some of the code duplication between platforms in the ways pointed out above.

**Comment by mrobinson** [comment]
@pcwalton I think the latest patch is working okay and does eliminate most of the duplicated code. How does it look to you?

**Comment by pcwalton** [comment]
@bors-servo: r+

Looks good!

**Comment by mrobinson** [comment]
The issue seems to be with the compilation of euclid:

```
/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/euclid-0.1.1/src/lib.rs:10:1: 10:39 error: unstable feature
/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/euclid-0.1.1/src/lib.rs:10 #![feature(asm, simd, zero_one, test)]
                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
error: aborting due to previous error
Could not compile `euclid`.
```

**Comment by Ms2ger** [comment]
Looks like you should update `.travis.yml` to run on nightly rather than stable.

**Comment by mrobinson** [comment]
r=pcwalton

**Pull request merged**
