### PR TITLE
Depend on servo-fontconfig-sys properly

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/skia/107)

### CODE REVIEW

**Comment by mrobinson** [comment]
I think you want to bump the version to 16, because the current one is 15.

**Comment by nox** [comment]
Ah...

**Comment by nox** [comment]
By the power of larsbors, I'll merge this by hand. Cc @larsbergstrom.

**Comment by nox** [comment]
https://travis-ci.org/servo/skia/builds/151165462

**Pull request merged**
