### PR TITLE
Simplify TOML syntax

### PR DESCRIPTION
**Pull request by UK992**
This change is [Reviewable](https://reviewable.io/reviews/servo/skia/96)

### CODE REVIEW

**Comment by nox** [comment]
Seems good, modulo one nit.

<details><summary><i>Previously, UK992 wrote…</i></summary>
> #### Simplify TOML syntax
> 
> 
> 
> 
> </details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Cargo.toml, line 34 \[r1\]](https://reviewable.io:443/reviews/servo/skia/96#-KHjObGG5HY8QPegNYKb:-KHjObGHhtYg2ueXOVQw:1620010194) ([raw file](https://github.com/servo/skia/blob/9f7149316e3c3d53578ffd9948617225fefe8056/Cargo.toml#L34)):*
> ```TOML
> expat-sys = "2.1.1"
> 
> [target.'cfg(not(target_os = "macos"))'.dependencies]
> ```

Could you do `cfg(any(target_os = "linux", target_os = "windows))` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/skia/96#-:-KHjOke2TWt46w6Uqd9X:-500831716)*

**Comment by UK992** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Cargo.toml, line 34 \[r1\]](https://reviewable.io:443/reviews/servo/skia/96#-KHjObGG5HY8QPegNYKb:-KHjPIwt6VCbtICdGGDK:-1163767251) ([raw file](https://github.com/servo/skia/blob/9f7149316e3c3d53578ffd9948617225fefe8056/Cargo.toml#L34)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Could you do `cfg(any(target_os = "linux", target_os = "windows))` instead?</details>
Android also use fontconfig and freetype-sys, should i add ``cfg(any(target_os = "android", target_os = "linux", target_os = "windows"))`` instead or keep it as it is?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/skia/96)*

**Comment by nox** [comment]
Oh right. I think it would be better to not have a negation in there yes.

**Comment by UK992** [comment]
Fixed.

**Comment by nox** [comment]
@bors-servo r+

<details><summary><i>Previously, UK992 wrote…</i></summary>
> Fixed.</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/skia/96#-:-KHjjjJxxlbc8BgWkIaT:1236647940)*

**Pull request merged**
