### PR TITLE
Enable NEON optimizations

### PR DESCRIPTION
**Pull request by metajack**
These were previously not compiled in.

[Review on Reviewable](https://reviewable.io/reviews/servo/skia/66)

### CODE REVIEW

**Comment by metajack** [comment]
This now compiles but Servo crashes on startup on Android.

@mbrubeck @glennw @larsbergstrom ideas?

**Comment by metajack** [comment]
This compiles now. Still trying to verify the NEON is used at runtime.

**Comment by metajack** [comment]
Confirmed they are being used. Ready for r? @mrobinson or @glennw

**Comment by glennw** [comment]
Looks good, so long as it builds on desktop still, r=me

**Pull request merged**
