### PR TITLE
CMakeLists: check for `i686` rather than `i386`

### PR DESCRIPTION
**Pull request by antrik**
This fixes build on my 32 bit x86 (Debian testing) system, which got
broken in the transition to CMake.

I'm not sure whether this shouldn't actually read `i386|i486|i586|i686`,
to cover all possibilities -- but it was just `i686` in the old
(non-CMake) `Makefile.cargo`; so unless CMake somehow munges this, I'm
assuming just `i686` is still fine...

---
This change is [Reviewable](https://reviewable.io/reviews/servo/skia/121)

### CODE REVIEW

**Comment by antrik** [comment]
Internal compiler error in nightly on macos... I'm pretty sure I'm not to blame for this one :-)

**Comment by larsbergstrom** [comment]
@bors-servo r+

That's fine. At some point, we should expand our target triple support, but I'd prefer to do so deliberately across all of our dependencies rather than making you add a bunch more piecemeal in this one PR. Thanks for the fix!

**Comment by larsbergstrom** [comment]
@bors-servo retry
- was a rustup.sh issue

**Comment by antrik** [comment]
This ICE seems reproducible. Anyone knows what's up with this? Does it really only affect this PR?...

**Comment by larsbergstrom** [comment]
@antrik Appears to be https://github.com/rust-lang/rust/issues/36816

**Comment by antrik** [comment]
Newer nightlies are available at last. Another retry please?

**Comment by emilio** [comment]
Sure.

@bors-servo: retry

**Pull request merged**
