### PR TITLE
Split out GLContext from GLRasterizationContext

### PR DESCRIPTION
**Pull request by mrobinson**
This will allow Servo to preserve the same GLContext and GrContext
between rasterization targets, thus vastly improving the performance of
OpenGL rasterization.

[Review on Reviewable](https://reviewable.io/reviews/servo/skia/60)

### CODE REVIEW

**Comment by mrobinson** [comment]
@pcwalton r?

**Comment by mrobinson** [comment]
Hrm. The build failure seems unrelated:
```
error: failed to resolve. Could not find `LocalSource` in `syntax::ast` [E0433]
/home/travis/.cargo/registry/src/github.com-0a35038f75765ae4/aster-0.3.3/src/stmt.rs:60             source: ast::LocalSource::LocalLet,
```

@bors-servo retry

**Comment by jdm** [comment]
It's probably because there's no Cargo.lock being used and it's grabbing the latest version of `aster` as a dependency of `serde`.

**Comment by mrobinson** [comment]
@jdm So what do you think the best way forward is here? I'm happy to check in a Cargo.lock file if we want to start doing that for dependencies.

**Comment by mrobinson** [comment]
@jdm @metajack I'm confused by this failure. It's a compilation failure in aster, which is a leaf dependency which only depends on rust. I don't seem to have any issues compiling either serde or aster alone using mach.

Could this be because of a difference in the version of rustc? Locally mach pulls down 
```
rustc 1.3.0-dev (fddfd089b 2015-07-10)
```

but it seems that travis is using:
```
rustc 1.3.0-nightly (8b835572b 2015-07-27)

```

**Comment by mrobinson** [comment]
And indeed ast:LocalSource was removed from rust 2 days ago: https://github.com/rust-lang/rust/pull/27297

**Comment by mrobinson** [comment]
Since the issue appears to be with aster upstream, @mbrubeck suggested pushing the "merge pull request" button manually. Does that seem like a appropriate approach here?

**Comment by metajack** [comment]
As I said in IRC, the correct thing is to pin Travis to use a working version of nightly. So add
```
rust: nightly-$date
```
to `.travis.yml`, where `$date` is the date of a working rustc. That should solve this problem, although the serde = "*" in euclid is going to potentially bite us down the road as well.

**Pull request merged**
